# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('begin_date', models.DateField(verbose_name='预订的起始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('days', models.IntegerField(verbose_name='预订的总天数')),
                ('house_price', models.IntegerField(verbose_name='房屋单价')),
                ('amount', models.IntegerField(verbose_name='订单总金额')),
                ('status', models.SmallIntegerField(choices=[(0, 'WAIT_ACCEPT'), (1, 'WAIT_PAYMENT'), (2, 'PAID'), (3, 'WAIT_COMMENT'), (4, 'COMPLETE'), (5, 'CANCELED'), (6, 'REJECTED')], db_index=True, default=0, verbose_name='订单状态')),
                ('comment', models.TextField(null=True, verbose_name='订单的评论信息或者拒单原因')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.House', verbose_name='预订的房间编号')),
            ],
            options={
                'db_table': 'tb_order',
            },
        ),
    ]
